FROM fedora:rawhide
MAINTAINER kirubakaran.keeran@qubecinema.com

RUN yum update -y
RUN yum install vsftpd net-tools which wget libdb-utils -y
RUN yum clean all

#Move the configs files to there respective directories.
COPY vsftpd_confs/vsftpd_user.txt /etc/vsftpd/
COPY vsftpd_confs/vsftpd.conf /etc/vsftpd/
COPY vsftpd_confs/vsftpd.virtual /etc/pam.d/

RUN db_load -T -t hash -f /etc/vsftpd/vsftpd_user.txt /etc/vsftpd/vsftpd-virtual-users.db
RUN rm -v /etc/vsftpd/vsftpd_user.txt; chmod 600 /etc/vsftpd/vsftpd-virtual-users.db

RUN mkdir -p /home/vsftp/ftpuser; chown -R ftp:ftp /home/vsftp 

EXPOSE 21 20

CMD ["/usr/bin/vsftpd", "-o", "background=NO"]

