FROM fedora:latest
MAINTAINER kirubakaran.keeran@qubecinema.com

RUN yum update -y\
	yum install vsftpd net-tools which \
	yum clean all

COPY vsftpd_confs/vsftpd_users.txt /etc/vsftpd/
COPY vsftpd_confs/vsftpd.conf /etc/vsftpd/
COPY vsftpd_confs/vsftpd.virtual /etc/pam.d/

RUN db_load -T -t hash -f /etc/vsftpd/vsftpd_users.txt /etc/vsftpd/vsftpd-virtual-users.db
RUN rm -v /etc/vsftpd/vusers.txt; chmod 600 /etc/vsftpd/vsftpd-virtual-user.db

RUN mkdir -p /home/vsftp/ftpuser; chown -R ftp:ftp /home/vsftp 

EXPOSE 21 20

CMD ["/usr/bin/vsftpd", "-o", "background=NO"]

